version: "3.9"

services:
  web:
    build: . 
    ports: ["8080:80"]
    environment:
      DATABASE_URL: "mysql://symfony:symfony@db:3306/symfony"
    depends_on: [db]

  db:
    image: mariadb:11
    environment:
      MARIADB_DATABASE: symfony
      MARIADB_USER: symfony
      MARIADB_PASSWORD: symfony
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
